udo: required

services:
  - docker

before_install:
  - docker --version

language: java
script: 
  - docker --version
  - docker-compose --version
  - cd docker-images/oa-java-server/
  - ./build-docker-image.sh
  - cd ../oa-server-specs/
  - ./build-docker-image.sh
  - cd ../../docker-topologies/runtime
  - docker-compose up

