udo: required

services:
  - docker

before_install:
  - docker --version

language: java
script: 
  - docker --version
  - docker-compose --version
  - cd docker-topologies/runtime
  - docker-compose up

